apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    db: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      db: mongodb
  template:
    metadata:
      labels:
        db: mongodb
    spec:
      containers:
      - name: mongodb
        image: danielchowyc/mongodb
        ports:
        - containerPort: 27017
