apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    db: mongodb
spec:
  type: LoadBalancer
  selector:
    db: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
