apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    db: mongodb
spec:
  type: NodePort
  selector:
    db: mongodb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 27017
      nodePort: 30036
